language: node_js

node_js:
 - 8

notifications:
  email:
    recipients:
      - magic@wizardtales.com
    on_success: change
    on_failure: always
    on_start: false

os:
  - linux

matrix:
  fast_finish: true

sudo: false

cache:
  npm: true
  directories:
    - node_modules

